services:
  - type: web
    name: pci-backend
    env: python
    region: oregon
    plan: free
    branch: main
    rootDir: .
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    autoDeploy: true
